spring:
  application:
    name: Taco
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: Aa123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      schema-locations: classpath:data/data.sql
  thymeleaf:
    prefix: classpath:/templates/

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
  file:
    name: Taco.log
    path: logs/


mybatis:
  mapper-locations: classpath:/mybatis/*.xml
server:
  port: 8080
taco:
  design:
    page-size: 20